import { useEffect, useMemo, useState } from 'react'
import { LuArrowLeft, LuBookOpen, LuCamera, LuFilm, LuMapPinned, LuNetwork, LuRefreshCw, LuSearch, LuShieldCheck, LuSparkles, LuUpload, LuUsers, LuZap } from 'react-icons/lu'

type Language = 'en' | 'es'
type TutorialMedia = { type: 'image' | 'video'; src: string; alt: string }
type Tutorial = { id:string; category:string; title:string; summary:string; steps:string[]; media:TutorialMedia[]; Icon:any }

function TutorialsPage({ language, onOpenOnboarding }: { language: Language; onOpenOnboarding?: () => void }) {
  const es = language === 'es'
  const [query,setQuery]=useState('')
  const [category,setCategory]=useState('all')
  const [selected,setSelected]=useState<Tutorial|null>(null)
  const [expandedImage,setExpandedImage]=useState<TutorialMedia|null>(null)
  const lang = es ? 'es' : 'en'
  const tutorials: Tutorial[] = es ? [
    {id:'start',category:'basics',title:'Crear una campaña',summary:'Creá tu campaña y entendé las secciones principales.',steps:['Creá una campaña desde el panel principal.','Completá sistema, nombre de la party y fecha de inicio.','Usá la barra lateral para moverte entre la crónica y sus entidades.'],media:[{type:'image',src:`/tutorials/create-campaign/campaign-creation-${lang}.png`,alt:'Creación de campaña'}],Icon:LuBookOpen},
    {id:'import',category:'basics',title:'Importar una campaña',summary:'Traé una campaña existente sin cargar cada entidad por separado.',steps:['Abrí Importar campaña.','Pegá o cargá el contenido siguiendo el formato simplificado.','Revisá la vista previa antes de confirmar la importación.'],media:[{type:'video',src:`/tutorials/import-campaign/campaign-import-${lang}.webm`,alt:'Importación de campaña'}],Icon:LuUpload},
    {id:'update',category:'basics',title:'Actualizar una campaña',summary:'Sumá o actualizá información de una campaña existente sin borrar lo que ya tenés.',steps:['Desde una campaña existente abrí Actualizar campaña.','Pegá o cargá el documento de actualización.','Revisá la vista previa de elementos nuevos y actualizados.','Aplicá la actualización y comprobá los cambios en tu campaña.'],media:[{type:'video',src:`/tutorials/update-campaign/update-campaign-${lang}.webm`,alt:'Actualización de campaña'}],Icon:LuRefreshCw},
    {id:'entities',category:'campaign',title:'Personajes, NPCs y lugares',summary:'Organizá las piezas principales de tu mundo.',steps:['Entrá a la sección de la entidad que querés crear.','Agregá la información útil para tu mesa.','Volvé a esas entidades desde relaciones, mapas y herramientas del GM.'],media:[{type:'image',src:`/tutorials/entities/character-${lang}.png`,alt:'Personajes'},{type:'image',src:`/tutorials/entities/npcs-${lang}.png`,alt:'NPCs'}],Icon:LuUsers},
    {id:'relationships',category:'campaign',title:'Relaciones y facciones',summary:'Visualizá alianzas, rivalidades y conexiones de tu campaña.',steps:['Creá o elegí las entidades que querés conectar.','Arrastrá desde el conector de un nodo hacia otro.','Definí categoría, intensidad y dirección de la relación.'],media:[{type:'video',src:`/tutorials/relationships-factions/relationships-${lang}.webm`,alt:'Relaciones y facciones'}],Icon:LuNetwork},
    {id:'maps',category:'campaign',title:'Mapas y pins',summary:'Subí mapas y controlá qué información conoce la party.',steps:['Desde Herramientas del GM abrí Gestión de mapas y subí una imagen.','Usá Agregar pin y hacé clic en el punto del mapa que querés marcar.','Mantené mapas o pins en Solo GM hasta que quieras revelarlos.'],media:[{type:'video',src:`/tutorials/maps-pins/maps-pin-${lang}.webm`,alt:'Mapas y pins'}],Icon:LuMapPinned},
    {id:'gmtools',category:'gm',title:'Herramientas del GM',summary:'Prepará sesiones, secretos, pistas y tramas sin exponer información privada.',steps:['Abrí Herramientas del GM desde la barra lateral.','Prepará una sesión y vinculá entidades relevantes.','Usá GM Screen durante la partida y actualizá pistas, secretos y tramas.'],media:[{type:'video',src:`/tutorials/gm-tools/gm-tools-${lang}.webm`,alt:'Herramientas del GM'}],Icon:LuShieldCheck},
    {id:'quick',category:'workflow',title:'Captura rápida',summary:'Guardá una idea en segundos sin cortar el ritmo de la partida.',steps:['Pulsá Captura rápida.','Escribí la idea o dato que no querés perder.','Después podés organizarlo con más calma.'],media:[{type:'video',src:`/tutorials/quick-capture/quick-capture-${lang}.webm`,alt:'Captura rápida'}],Icon:LuZap},
  ] : [
    {id:'start',category:'basics',title:'Create a campaign',summary:'Create your campaign and learn the main sections.',steps:['Create a campaign from the main dashboard.','Add the system, party name and starting date.','Use the sidebar to move through the chronicle and its entities.'],media:[{type:'image',src:`/tutorials/create-campaign/campaign-creation-${lang}.png`,alt:'Campaign creation'}],Icon:LuBookOpen},
    {id:'import',category:'basics',title:'Import a campaign',summary:'Bring an existing campaign in without creating every entity manually.',steps:['Open Import campaign.','Paste or upload content using the simplified format.','Review the preview before confirming the import.'],media:[{type:'video',src:`/tutorials/import-campaign/campaign-import-${lang}.webm`,alt:'Campaign import'}],Icon:LuUpload},
    {id:'update',category:'basics',title:'Update a campaign',summary:'Add or update information in an existing campaign without deleting what is already there.',steps:['Open Update campaign from an existing campaign.','Paste or upload your update document.','Review the preview of new and updated items.','Apply the update and check the changes in your campaign.'],media:[{type:'video',src:`/tutorials/update-campaign/update-campaign-${lang}.webm`,alt:'Campaign update'}],Icon:LuRefreshCw},
    {id:'entities',category:'campaign',title:'Characters, NPCs and locations',summary:'Organize the main pieces of your world.',steps:['Open the section for the entity you want to create.','Add the information your table actually needs.','Reuse those entities from relationships, maps and GM tools.'],media:[{type:'image',src:`/tutorials/entities/character-${lang}.png`,alt:'Characters'},{type:'image',src:`/tutorials/entities/npcs-${lang}.png`,alt:'NPCs'}],Icon:LuUsers},
    {id:'relationships',category:'campaign',title:'Relationships and factions',summary:'Visualize alliances, rivalries and campaign connections.',steps:['Create or choose the entities you want to connect.','Drag from one node connector to another.','Choose category, intensity and direction.'],media:[{type:'video',src:`/tutorials/relationships-factions/relationships-${lang}.webm`,alt:'Relationships and factions'}],Icon:LuNetwork},
    {id:'maps',category:'campaign',title:'Maps and pins',summary:'Upload maps and control what the party knows.',steps:['Open Map Manager under GM Tools and upload an image.','Choose Add pin and click the point you want to mark.','Keep maps or pins GM only until you are ready to reveal them.'],media:[{type:'video',src:`/tutorials/maps-pins/maps-pin-${lang}.webm`,alt:'Maps and pins'}],Icon:LuMapPinned},
    {id:'gmtools',category:'gm',title:'GM Tools',summary:'Prepare sessions, secrets, clues and plot threads privately.',steps:['Open GM Tools from the sidebar.','Prepare a session and link relevant entities.','Use GM Screen during play and update clues, secrets and threads.'],media:[{type:'video',src:`/tutorials/gm-tools/gm-tools-${lang}.webm`,alt:'GM Tools'}],Icon:LuShieldCheck},
    {id:'quick',category:'workflow',title:'Quick Capture',summary:'Save an idea in seconds without interrupting play.',steps:['Press Quick Capture.','Write the idea or detail you do not want to lose.','Organize it properly later when you have time.'],media:[{type:'video',src:`/tutorials/quick-capture/quick-capture-${lang}.webm`,alt:'Quick Capture'}],Icon:LuZap},
  ]
  const cats = es ? [['all','Todos'],['basics','Primeros pasos'],['campaign','Organizar campaña'],['gm','Para GMs'],['workflow','Flujo de trabajo']] : [['all','All'],['basics','Getting started'],['campaign','Campaign organization'],['gm','For GMs'],['workflow','Workflow']]
  const filtered=useMemo(()=>tutorials.filter(t=>(category==='all'||t.category===category)&&(`${t.title} ${t.summary}`.toLowerCase().includes(query.toLowerCase()))),[tutorials,query,category])
  const mediaLabel=(t:Tutorial)=>t.media.length>1?(es?'2 capturas':'2 screenshots'):t.media[0]?.type==='video'?(es?'Video corto':'Short video'):(es?'Captura':'Screenshot')
  useEffect(()=>{
    const handleKeyDown=(event:KeyboardEvent)=>{
      if(event.key==='Escape'){
        if(expandedImage)setExpandedImage(null)
        else if(selected)setSelected(null)
      }
    }
    window.addEventListener('keydown',handleKeyDown)
    return ()=>window.removeEventListener('keydown',handleKeyDown)
  },[expandedImage,selected])
  return <main className="tutorials-page">
    <button className="public-back-button" onClick={()=>window.history.back()}><LuArrowLeft/><span>{es?'Volver':'Back'}</span></button>
    <section className="tutorials-hero"><span className="public-info-eyebrow"><LuSparkles/> {es?'Centro de tutoriales':'Tutorial Center'}</span><h1>{es?'Aprendé Campaign Chronicles a tu ritmo.':'Learn Campaign Chronicles at your own pace.'}</h1><p>{es?'Guías cortas y prácticas. Entrá solo a la función que necesitás y volvé a tu campaña.':'Short, practical guides. Open only what you need and get back to your campaign.'}</p></section>
    {onOpenOnboarding&&<div className="tutorial-onboarding-replay"><button type="button" onClick={onOpenOnboarding}><LuSparkles/>{es?'Volver a ver la introducción':'Replay introduction'}</button></div>}
    <div className="tutorials-toolbar"><label><LuSearch/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={es?'Buscar un tutorial...':'Search tutorials...'}/></label><div className="tutorials-cats">{cats.map(([id,label])=><button className={category===id?'active':''} onClick={()=>setCategory(id)} key={id}>{label}</button>)}</div></div>
    <section className="tutorials-grid">{filtered.map(t=><button className="tutorial-card" key={t.id} onClick={()=>setSelected(t)}><span className="tutorial-card-icon"><t.Icon/></span><span className="tutorial-card-copy"><strong>{t.title}</strong><small>{t.summary}</small><em>{t.media[0]?.type==='video'?<LuFilm/>:<LuCamera/>}{mediaLabel(t)}</em></span></button>)}</section>
    {!filtered.length&&<p className="tutorials-empty">{es?'No encontramos tutoriales con esa búsqueda.':'No tutorials match that search.'}</p>}
    {selected&&<div className="tutorial-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setSelected(null)}}><article className="tutorial-modal"><button className="tutorial-close" onClick={()=>setSelected(null)} aria-label={es?'Cerrar':'Close'}>×</button><span className="tutorial-modal-icon"><selected.Icon/></span><h2>{selected.title}</h2><p>{selected.summary}</p><ol>{selected.steps.map((s,i)=><li key={s}><span>{i+1}</span><p>{s}</p></li>)}</ol><div className={`tutorial-media-grid ${selected.media.length>1?'tutorial-media-grid--multi':''}`}>{selected.media.map((media)=>media.type==='video'?<video key={media.src} className="tutorial-media" autoPlay muted loop playsInline preload="auto" aria-label={media.alt}><source src={media.src} type="video/webm" />{es?'Tu navegador no puede reproducir este video.':'Your browser cannot play this video.'}</video>:<button key={media.src} type="button" className="tutorial-image-button" onClick={()=>setExpandedImage(media)} aria-label={es?`Ampliar ${media.alt}`:`Enlarge ${media.alt}`}><img className="tutorial-media" src={media.src} alt={media.alt} loading="lazy" /><span className="tutorial-image-hint">{es?'Clic para ampliar':'Click to enlarge'}</span></button>)}</div></article></div>}
    {expandedImage&&<div className="tutorial-lightbox" role="dialog" aria-modal="true" aria-label={expandedImage.alt} onMouseDown={e=>{if(e.currentTarget===e.target)setExpandedImage(null)}}><button className="tutorial-lightbox-close" onClick={()=>setExpandedImage(null)} aria-label={es?'Cerrar imagen':'Close image'}>×</button><img src={expandedImage.src} alt={expandedImage.alt} /></div>}
  </main>
}
export default TutorialsPage
